name: Architect Preview Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - closed

env:
  ARCHITECT_GENERATED: true
  ARCHITECT_PREVIEW: true
  PREVIEW_PREFIX: preview-
  PREVIEW_TAG: preview-${{ github.event.number }}
  PREVIEW_MAINLINE_BRANCH: master
  COMPONENT_FILE_PATH: architect.yml
  ARCHITECT_ACCOUNT: architect-ryan
  PLATFORM_NAME: architect
  COMPONENT_NAME: hello-world-test-12
  ENVIRONMENT_TTL: --ttl=4hours

jobs:
  architect_remove_preview:
    if: github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install Architect CLI
        run: sudo npm install -g @architect-io/cli
      - name: Set Architect API endpoint
        run: architect config:set api_host https://api.dev.architect.io
      - name: Set Architect registry endpoint
        run: architect config:set registry_host registry.dev.architect.io
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }}
      - name: Remove preview environment
        run: architect environment:destroy ${{ env.PREVIEW_TAG }} --auto-approve -f || exit 0
  architect_create_preview:
    if: github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - uses: crazy-max/ghaction-github-runtime@v2 # Exports internal envs for Github Actions. Required for register caching to work.
      - name: Install Architect CLI
        run: sudo npm install -g @architect-io/cli
      - name: Set Architect API endpoint
        run: architect config:set api_host https://api.dev.architect.io
      - name: Set Architect registry endpoint
        run: architect config:set registry_host registry.dev.architect.io
      - name: Login to Architect Cloud
        run: architect login -e ${{ secrets.ARCHITECT_EMAIL }} -p ${{ secrets.ARCHITECT_PASSWORD }} # These secrets were created on your behalf
      - name: Register component w/ Architect
        run: architect register ${{ env.COMPONENT_FILE_PATH }} -t ${{ env.PREVIEW_TAG }}
      - name: Create env if not exists
        run: architect environment:create ${{ env.PREVIEW_TAG }} --platform ${{ env.PLATFORM_NAME }} ${{ env.ENVIRONMENT_TTL }} || exit 0
      - name: Deploy component
        run: architect deploy --auto-approve -e ${{ env.PREVIEW_TAG }} ${{ env.COMPONENT_NAME }}:${{ env.PREVIEW_TAG }}
